#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Fix Gnome Apps Slow Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

remaps &		                                    # run the remaps script, switching caps/esc and more; check it for more info
setbg &			                                    # set the background with the `setbg` script
picom &												# picom for transparency
dunst &			                                    # dunst for notifications
unclutter --timeout 1 --jitter 10 &		            # Remove mouse when idle
mpd &												# Music Player Daemon for music ofc
mpdup &												# mpdup for updating the music player daemon, runs as a loop
sxhkd &                                             # shkd for non-modkey bindings
clipmenud &											# clipmenud because the X clipboard is pretty scuffed
nm-applet &											# network-manager-applet for, well... managing networks
setsid -f dwmblocks
