#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -v" \
	mv="mv -v" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	la="ls -a --color=auto --group-directories-first" \
	ll="ls -la --color=auto --group-directories-first" \
	grep="grep --color=auto" \
    fgrep="fgrep --color=auto" \
    egrep="egrep --color=auto" \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# Config files edit commands.
alias \
    i3c="nvim $HOME/.config/i3/config" \
    nvc="nvim $HOME/.config/nvim/init.vim" \
    zrc="nvim $HOME/.config/zsh/.zshrc" \
    zpf="nvim $HOME/.zprofile" \
    pbc="nvim $HOME/.config/polybar/config"


# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	trem="transmission-remote" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	z="zathura" \
    srr="xset r rate 170 40"

# Git aliases:
alias \
    g="git" \
    gst="git status" \
    gcl="git clone" \
    gpl="git pull" \
    gps="git push" \
    ga="git add" \
    gc="git commit" \
    gcm="git commit -m"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
