#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. I keep those commands in ~/.xprofile because
# that file is run automatically if someone uses a display manager (login
# screen) and so they are needed there. To prevent doubling up commands, I
# source them here with the line below.

# export STATUSBAR="i3blocks" # Uncomment this line when using i3.

[ -f ~/.xprofile ] && ./.xprofile

# Your default Minux WM is determined in your `~/.profile` on login.  Here we
# run the proper command to run when the graphical environment starts.

# Comment/uncomment these lines depending on what wm you want to use. Also
# check the i3blocks line above.

# GnuPG agent stuff yeah yeah
if [ -x /usr/bin/gpg-agent ]; then
	eval "$(/usr/bin/gpg-agent --daemon)"
fi

ssh-agent dwm
